export enum COLORS {
  TINT = 'tintColor',
  TAB_ICON_DEFAULT = 'tabIconDefault',
  TAB_ICON_SELECTED = 'tabIconSelected',
  TAB_BAR = 'tabBar',
  ERROR_BACKGROUND = 'errorBackground',
  ERROR_TEXT = 'errorText',
  WARNING_BACKGROUND = 'warningBackground',
  WARNING_TEXT = 'warningText',
  NOTICE_BACKGROUND = 'noticeBackground',
  NOTICE_TEXT = 'noticeText',
  LINK = 'link',
  GREEN_CARD = 'greenCard',
  YELLOW_CARD = 'yellowCard',
  ORANGE_CARD = 'orangeCard',
  PURPLE_CARD = 'purpleCard',
  RED_CARD = 'redCard',
  GREEN_OPACITY = 'greenOpacity',
  RED_OPACITY = 'redOpacity',
  YELLOW_OPACITY = 'yellowOpacity',
  WHITE = 'white',
  GREY = 'grey',
  JIRA = 'jira',
  LIGHT_GREY = 'lightgrey',
}

export const colors = {
  tintColor: '#2f95dc',
  tabIconDefault: '#ccc',
  tabIconSelected: '#2f95dc',
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#2f95dc',
  noticeText: '#fff',
  link: '#2e78b7',
  greenCard: '#36802D',
  yellowCard: '#E9D700',
  orangeCard: '#FF6600',
  purpleCard: '#E3007D',
  redCard: '#F80100',
  greenOpacity: 'rgba(54, 128, 45, 0.3)',
  redOpacity: 'rgba(217, 30, 24, 0.3)',
  yellowOpacity: 'rgba(245, 229, 27, 0.3)',
  white: 'white',
  lightgrey: 'lightgrey',
  jira: '#0747A6',
};
