import {
  JIRA_URL, JIRA_EMAIL, JIRA_TOKEN,
  FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_DATABASE_URL, FIREBASE_STORAGE_BUCKET,
} from 'react-native-dotenv';

export default {
  JIRA_URL, JIRA_EMAIL, JIRA_TOKEN,
  FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_DATABASE_URL, FIREBASE_STORAGE_BUCKET,
};
